---
- name: "Create pre-requisites for the Molecule environment"
  hosts: localhost
  vars:
    collection_dir: /workspaces/ansible-molecule/ansible_collections
    role_dir: example/web/roles
    molecule_dir: example/web/extensions/molecule
    compacted_file: /workspaces/ansible-molecule/molecule_default.tar.gz
  tasks:

    - name: "Create the directory structure"
      ansible.builtin.file:
        path: "{{ collection_dir }}"
        state: directory

    - name: "Create a custom ansible.cfg"
      ansible.builtin.copy:
        content: |
                 [defaults]
                 collections_path = /root/.ansible/collections/ansible_collections:/usr/share/ansible/collections/ansible_collections:{{ collection_dir }}
        dest: "/root/.ansible.cfg"

    - name: "Check for collection dir existence"
      stat: path={{ collection_dir }}/example/web
      register: coldir

    - name: "Check for role dir existence"
      stat: path={{ collection_dir }}/{{ role_dir }}/install_apache
      register: roledir

    - name: "Create a new collection skeleton"
      ansible.builtin.shell: "ansible-galaxy collection init example.web --init-path {{ collection_dir }}/"
      when: not coldir.stat.exists

    - name: "Create a new role skeleton"
      ansible.builtin.shell: "ansible-galaxy role init install_apache --init-path {{ collection_dir }}/{{ role_dir }}/"
      when: not roledir.stat.exists

    - name: "Install podman collection"
      ansible.builtin.shell: "ansible-galaxy collection install containers.podman -p /workspaces/ansible-molecule"

    - name: "Create the molecule structure"
      ansible.builtin.file:
        path: "{{ collection_dir }}/{{ molecule_dir }}"
        state: directory

    # - name: "Extract molecule content to default dir"
    #   ansible.builtin.unarchive:
    #     src: "{{ compacted_file }}"
    #     dest: "{{ collection_dir }}/{{ molecule_dir }}"

    - name: "Insert the install apache task"
      ansible.builtin.copy:
        content: |
                 ---
                 # tasks file for install_apache
                 - name: Install apache
                   ansible.builtin.package:
                     name: httpd
                     state: installed
        dest: "{{ collection_dir }}/{{ role_dir }}/install_apache/tasks/main.yml"
