---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: centos_stream_9
    image: quay.io/centoshyperscale/centos:stream9
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest

driver:
  options:
    managed: False
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

